import Foundation
import CoreGraphics
import AppKit

/// Sends synthetic scroll events to the system.
struct ScrollEngine {

    /// Sends a vertical scroll event with the given number of lines.
    /// Positive = up, negative = down.
    
    private static let headFlowEventTag: Int64 = 0x48464C57 // "HFLW"

    static func isHeadFlowEvent(_ event: CGEvent) -> Bool {
        event.getIntegerValueField(.eventSourceUserData) == headFlowEventTag
    }
    
    static func scrollLines(_ lines: Int32) {
        guard let source = CGEventSource(stateID: .hidSystemState) else {
            return
        }

        guard let event = CGEvent(
            scrollWheelEvent2Source: source,
            units: .line,
            wheelCount: 1,
            wheel1: lines,
            wheel2: 0,
            wheel3: 0
        ) else {
            return
        }

        // Mark this CGEvent as generated by HeadFlow.
        event.setIntegerValueField(.eventSourceUserData, value: headFlowEventTag)

        event.post(tap: .cghidEventTap)
    }

    static func scrollDown(lines: Int32) {
        scrollLines(-lines)
    }

    static func scrollUp(lines: Int32) {
        scrollLines(lines)
    }

    /// Opens System Settings → Privacy & Security → Accessibility.
    static func openAccessibilitySettings() {
        if let url = URL(
            string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"
        ) {
            NSWorkspace.shared.open(url)
        }
    }
}
